[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "langchain-predictionguard"
authors = [{name = "Jacob Mansdorfer", email = "jacob@predictionguard.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
description-file = "README.md"
dependencies = [
    "predictionguard<3.0.0,>=2.7.0",
    "langchain-core<0.4.0,>=0.3.25",
    "langchain-community<0.4.0,>=0.3.12"
]

[project.urls]
Home = "https://predictionguard.com"