name: branch-test

on:
  pull_request:
    branches:
      - main

jobs:

  tests:
    name: Installing requirements and testing functions
    runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Install poetry
        run: |
          python -m pip install poetry==1.8.5

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Run Linting
        run: |
          python -m poetry run ruff check

      - name: Run tests
        run: |
          python -m poetry run python -m pytest -sxv
        env:
          PREDICTIONGUARD_API_KEY: ${{ secrets.PREDICTIONGUARD_API_KEY }}